dashboard_import:
  package_import_url: github://ApolloAutomation/BTN-1/Integrations/ESPHome/BTN-1_Minimal.yaml
  import_full_config: false

ota:
  - platform: esphome
    id: ota_esphome

wifi:
  ap:
    ssid: "Apollo BTN-1 Hotspot"

logger:

packages:
  core: !include Core.yaml